[package]
name = "spin-llm"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
anyhow = "1.0"
bytesize = "1.1"
llm = { git = "https://github.com/rustformers/llm.git", rev = "2f6ffd4435799ceaa1d1bcb5a8790e5b3e0c5663", features = [
	"llama",
	"metal",
] }
lru = "0.9.0"
spin-app = { path = "../app" }
spin-core = { path = "../core" }
spin-world = { path = "../world" }
tracing = { workspace = true }
tokio = { version = "1", features = ["macros", "sync"] }
rand = "0.8.5"
uuid = { version = "1.4.1", features = ["v4"] }
chrono = "0.4.26"
